'''
Created on 2017. 7. 26.

Even Fibonacci numbers
Problem 2 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Answer 2
1089154

@author: sharb
'''

p = 1
n = 2
s = 0
while s < 1000000:
    s += n
    p, n = 2 * n + p, 3 * n + 2 * p
print (s)
